---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^user/cparser/testdata/
      - id: end-of-file-fixer
        exclude: ^user/cparser/testdata/
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^user/cparser/testdata/
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
      - id: clang-format
        exclude: ^user/cparser/testdata/
