name: golangci-lint
on:
  push:
    paths:
      - user/**
    branches:
      - master
      - main
  pull_request:
    paths:
      - user/**

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: user/go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          working-directory: user
