name: golangci-lint
on:
  push:
    paths:
      - user/**
    branches:
      - master
      - main
  pull_request:
    paths:
      - user/**

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: user/go.mod
          cache: false
      - run: sudo apt install -y bison
      - run: go generate -v ./...
        working-directory: user
      - name: Run unit tests
        run: go test -v ./pkg/...  # cparser tests don't work yet on Github Actions
        working-directory: user
